kind = "web"
previewPath = "/"
title = "Super TV"
version = "1.0.0"
id = "artifacts/super-tv"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19603

[services.development]
run = "pnpm --filter @workspace/super-tv run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/super-tv", "run", "build" ]
publicDir = "artifacts/super-tv/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19603"
BASE_PATH = "/"
